//>>excludeStart("jqmBuildExclude", pragmas.jqmBuildExclude);
//>>group: exclude

define([
	"require",
	"./widgets/loader",
	"./events/navigate",
	"./navigation/path",
	"./navigation/history",
	"./navigation/navigator",
	"./navigation/method",
	"./transitions/handlers",
	"./transitions/visuals",
	"./jquery.mobile.navigation",
	"./jquery.mobile.degradeInputs",
	"./widgets/dialog",
	"./widgets/collapsible",
	"./widgets/collapsibleSet",
	"./jquery.mobile.fieldContain",
	"./jquery.mobile.grid",
	"./widgets/navbar",
	"./widgets/listview",
	"./widgets/listview.filter",
	"./widgets/listview.autodividers",
	"./jquery.mobile.nojs",
	"./widgets/forms/checkboxradio",
	"./widgets/forms/button",
	"./widgets/forms/slider",
	"./widgets/forms/rangeslider",
	"./widgets/forms/textinput",
	"./widgets/forms/select.custom",
	"./widgets/forms/select",
	"./jquery.mobile.buttonMarkup",
	"./widgets/controlgroup",
	"./jquery.mobile.links",
	"./widgets/toolbar",
	"./widgets/fixedToolbar",
	"./widgets/fixedToolbar.workarounds",
	"./widgets/popup",
	"./widgets/panel",
	"./widgets/table",
	"./widgets/table.columntoggle",
	"./widgets/table.reflow",
	"./widgets/jquery.ui.tabs",
	"./widgets/tabs",
	"./jquery.mobile.zoom",
	"./jquery.mobile.zoom.iosorientationfix"
], function( require ) {
	require( [ "./jquery.mobile.init" ], function() {} );
});
//>>excludeEnd("jqmBuildExclude");
